test_task:
  matrix:
    container:
      image: rustlang/rust:nightly
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  before_build_script:
    - apt-get update && apt-get install -y qemu-system
    - cargo install bootimage
    - rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - rustup component add llvm-tools-preview
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index