language: rust
rust:
  - nightly

cache: cargo

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo install bootimage
  - cargo install cargo-audit

script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  # This is a workaround for no_std and std tests being in the same crate
  - cd kernel & cargo build
  - cd kernel & cargo buildcargo test
  - cargo audit

addons:
  apt:
    update: true
    packages:
      - qemu-system