[package]
name = "thanatos"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["bootimage", "kernel"]

[dependencies]
bootimage = {path = "bootimage"}
[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
